people:
  people:
    host: https://people.cit.com.br
    user: 
    pass: 
  gateway:
    host: https://wsgateway.cit.com.br
    app_token: Blpy2nNXnjya

techgallery:
  endpoint: https://tech-gallery.appspot.com/_ah/api/rest/v1

knowledgemap:
  flags: 

repository:
  elasticsearch:
    #host: http://localhost:9200
    host: http://104.197.92.45:9200
